version: '3'
services:
  db:
      container_name: db
      volumes:
       - db-data:/var/lib/mysql
      image: 'mysql'
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: test
      ports:
          - '3306:3306'
      networks:
        - management

    
    


  phpmyadmin:
      container_name: phma
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          PMA_HOST: db
          UPLOAD_LIMIT: 300M
      networks:
        - management



networks:
  management:
    driver: bridge

volumes:
  db-data:
